name: Build and deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    name: Create Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: ./dist

  deploy:
    name: Deploy Build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Release
        uses: actions/download-artifact@v3
        with:
          name: web-release

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./